spring:
  cloud:
    gateway:
      mvc:
        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins:
                - "http://localhost:3000"
                - "http://localhost:3001"
              allowed-methods: "*"
              allowed-headers: "*"
              allow-credentials: true