spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: incident-service
          uri: lb://incident-service
          predicates:
            - Path=/api/incidents/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true