# Port sur lequel le service va écouter
server.port=8082

# Nom du service (utile pour le prochain sprint)
spring.application.name=comment-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Connexion à pgAdmin/PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_incidents_db
spring.datasource.username=postgres
spring.datasource.password= hafssa

# JPA / Hibernate : Création automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
