version: '3.9'

networks:
  incidents-network:
    driver: bridge

volumes:
  minio_data:

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: incidents-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak_db
      KC_DB_USERNAME: incidents_user
      KC_DB_PASSWORD: incidents_pass
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8180:8080"
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - incidents-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # accès au PostgreSQL local

  minio:
    image: minio/minio:latest
    container_name: incidents-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_pass_2024
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - incidents-network