server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # ne s'enregistre pas lui-même
    fetch-registry: false         # ne récupère pas la liste des services
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0  # démarrage rapide en dev

management:
  endpoints:
    web:
      exposure:
        include: health,info