server:
  port: 8081

spring:
  application:
    name: incident-service

  datasource:
    # L'adresse de ta base de données (que tu dois créer dans pgAdmin avant)
    url: jdbc:postgresql://localhost:5432/db_incidents?currentSchema=manage # Remplace "db_incidents" par le nom de ta base de données PostgreSQL et "manage" par le nom de ton schéma si tu en as un
    username: postgres
    password: Mon_Mot_De_Passe # Remplace par ton mot de passe PostgreSQL
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        # On dit explicitement à Hibernate d'utiliser ce schéma par défaut
        default_schema: manage

    hibernate:
      ddl-auto: update # Très important : Spring créera la table "incident" tout seul !
    show-sql: true # Pour voir les commandes SQL dans ton terminal



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka