server:
  port: 8081

spring:
  application:
    name: incident-service

  datasource:
    # L'adresse de ta base de données (que tu dois créer dans pgAdmin avant)
    url: jdbc:postgresql://localhost:5432/db_incidents?currentSchema=manage 
    username: postgres
    password: you_said_we_should_not_put_passwords_in_code
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        # On dit explicitement à Hibernate d'utiliser ce schéma par défaut
        default_schema: manage

    hibernate:
      ddl-auto: update # Très important : Spring créera la table "incident" tout seul !
    show-sql: true # Pour voir les commandes SQL dans ton terminal



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka