server:
  port: 8081

spring:
  application:
    name: incident-service

  datasource:
    # L'adresse de ta base de données (que tu dois créer dans pgAdmin avant)
    url: jdbc:postgresql://localhost:5432/db_incidents?currentSchema=public # Remplace "db_incidents" par le nom de ta base de données PostgreSQL et "manage" par le nom de ton schéma si tu en as un
    username: postgres
    password: hafssa  # Remplace par ton mot de passe PostgreSQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
